#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate an OSMO workflow of independent, shard-safe geometry-ablation tasks.

Each task owns exactly one (suite, variant) output prefix.  This is intentionally independent
task parallelism, not TorchRun: a 3dgrut reconstruction is single-GPU, while the ablation cells
are embarrassingly parallel.  The emitted YAML assumes an image with this checkout at
``/workspace/3dgrut`` and the optional MoGe/RADIO dependencies already installed.
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_geometry_ablation import VARIANTS  # noqa: E402


def quote(value: str) -> str:
    return shlex.quote(value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="Destination OSMO workflow YAML")
    parser.add_argument("--image", required=True, help="Pinned container image, including the checked-out branch")
    parser.add_argument(
        "--dataset-url", required=True, help="OSMO-readable object-store URL containing the data layout"
    )
    parser.add_argument("--output-url", required=True, help="Object-store prefix for isolated task outputs")
    parser.add_argument(
        "--cache-url", default=None, help="Optional prewarmed cache-root URL; must contain suite/scene directories"
    )
    parser.add_argument("--dataset-scale", choices=("reduced", "full"), default="reduced")
    parser.add_argument("--suites", default="ob3d,dtu,tnt")
    parser.add_argument(
        "--variants", default=None, help="Comma-separated variant subset; default is the full 13-condition matrix"
    )
    parser.add_argument(
        "--pool", default=None, help="Optional pool to select at submission time (recorded as a comment)"
    )
    parser.add_argument("--platform", default=None, help="Optional OSMO platform, e.g. dgx-h100")
    parser.add_argument("--gpu", type=int, default=1)
    parser.add_argument("--cpu", type=int, default=16)
    parser.add_argument("--memory", default="128Gi")
    parser.add_argument("--storage", default="300Gi")
    parser.add_argument("--moge3-model", default="/opt/models/moge-3-vitl/model.pt")
    parser.add_argument("--radio-repo", default="/opt/RADIO")
    args = parser.parse_args()

    suites = tuple(value.strip() for value in args.suites.split(",") if value.strip())
    if set(suites) - {"ob3d", "dtu", "tnt"}:
        raise SystemExit(f"Unknown suites: {sorted(set(suites) - {'ob3d', 'dtu', 'tnt'})}")
    by_name = {variant.name: variant for variant in VARIANTS}
    names = (
        tuple(value.strip() for value in args.variants.split(",") if value.strip()) if args.variants else tuple(by_name)
    )
    unknown = set(names) - set(by_name)
    if unknown:
        raise SystemExit(f"Unknown variants: {sorted(unknown)}")

    resource = [
        "  resources:",
        "    geometry:",
        f"      gpu: {args.gpu}",
        f"      cpu: {args.cpu}",
        f"      memory: {args.memory}",
        f"      storage: {args.storage}",
    ]
    if args.platform:
        resource.append(f"      platform: {args.platform}")
    lines = [
        "# Generated by scripts/ablation/generate_osmo_geometry_ablation.py; do not hand-edit.",
        "# Submit: osmo workflow submit <this-file>" + (f" --pool {args.pool}" if args.pool else ""),
        "workflow:",
        f"  name: geometry-ablation-30k-{args.dataset_scale}",
        *resource,
        "  tasks:",
    ]
    for suite in suites:
        for name in names:
            task = f"{suite}-{name}".replace("_", "-")
            output_url = args.output_url.rstrip("/") + f"/shards/{suite}/{name}"
            cache_input = ["      - url: " + args.cache_url.rstrip("/")] if args.cache_url else []
            cache_root = "{{input:1}}" if args.cache_url else "{{output}}/results/cache"
            data = "{{input:0}}"
            training_command = " ".join(
                [
                    ".venv/bin/python scripts/ablation/run_geometry_ablation.py",
                    "--out-dir '{{output}}/results'",
                    f"--dataset-scale {args.dataset_scale}",
                    f"--suites {suite}",
                    f"--variants {name}",
                    f"--moge3-model {quote(args.moge3_model)}",
                    f"--cache-root '{cache_root}'",
                    f"--ob3d-root '{data}/ob3d/OB3D_colmap'",
                    f"--dtu-root '{data}/dtu_dataset/dtu'",
                    f"--dtu-eval-root '{data}/dtu_dataset/dtu_eval'",
                    f"--tnt-root '{data}/tnt_dataset/tnt'",
                    f"--tnt-reconstruction-root '{data}/tnt_dataset/tnt_gof'",
                    "--resume",
                ]
            )
            command = "\n".join(
                [
                    "set -euo pipefail",
                    "cd /workspace/3dgrut",
                    "export CUDA_VISIBLE_DEVICES=0",
                    f"export THREEDGRUT_RADIO_REPO={quote(args.radio_repo)}",
                    "export PYTHONPATH=/opt/MoGe:/opt/meshdeps:${PYTHONPATH:-}",
                    training_command,
                ]
            )
            lines += [
                f"  - name: {task}",
                "    resource: geometry",
                f"    image: {args.image}",
                "    inputs:",
                f"      - url: {args.dataset_url}",
                *cache_input,
                "    outputs:",
                f"      - url: {output_url}",
                "        path: results",
                "    checkpoint:",
                "      - path: results/runs",
                f"        url: {args.output_url.rstrip('/')}/checkpoints/{suite}/{name}",
                "        frequency: 10m",
                "    command: [bash, -lc]",
                "    args:",
                "      - |",
                *(f"        {line}" for line in command.splitlines()),
            ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.output} with {len(suites) * len(names)} independent GPU tasks.")


if __name__ == "__main__":
    main()
